# supabase/config.toml

[functions.cleanup-pending-invitations]
# "cron" を "schedule" に修正します
schedule = "0 18 * * *"

[db.config]
# .env ファイルの POSTGRES_DB_JWT_SECRET の値を
# 'custom.jwt_secret' という名前の変数としてデータベース内で使えるようにする
"custom.jwt_secret" = "env.POSTGRES_DB_JWT_SECRET"